os: linux
language: php
dist: xenial
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - 8.1
  - nightly

before_script:
  - composer install --no-interaction --prefer-source --dev
  - phpenv rehash
script:
  - XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-text
  - ./vendor/bin/phpcs --standard=PEAR src/
