name: Mutation tests
on:
  push:
  workflow_dispatch:
  pull_request:

jobs:

  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions:
          - '8.2'
          - '8.3'

    name: using PHP ${{ matrix.php-versions }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          coverage: "pcov"
          php-version: ${{ matrix.php-versions }}
          ini-values: memory_limit=-1, zend.assertions=1

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ matrix.php-versions }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-${{ matrix.php-versions }}-

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Add infection dependency
        run: composer require --dev roave/infection-static-analysis-plugin

      - name: Infection
        run: "vendor/bin/roave-infection-static-analysis-plugin --threads=$(nproc)"
